# Jekyll configuration
# ---
title: Scroll Btween # title of the documentation
description: >- # Description of the docs. (>- means to ignore newlines until next param)
  Scroll Btween uses scroll position of document - or any DOM element - to tween CSS values on any DOM element.
baseurl: "/scroll-btween/_site" # the subpath of your site, e.g. /blog
url: "http://localhost" # the base hostname & protocol for your site, e.g. http://example.com
#permalink: /:path/:basename/:output_ext
#destination: ../marcelrent/public/proto-app # Build relative path destination. The destination directory e.g. /blog
#keep_files: [cache]
#markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true
sass:
    style: compressed
#exclude: ['/misc']


# LibDoc configuration
# ---

# Metadata informations for the project
metadata:
    # Sets the language of the project, default is en
    #lang: en
    # PNG favicon URL. Can be either relative URL from site root or absolute URL starting with 'http'. Default is LibDoc's favicon
    #favicon: 
    # Name of the author of the project, used into various places of the theme like footer. Default is empty
    author: Olivier Blanc
    # Theme color metadata used in some browsers like Chrome that applies this color on browser address bar.
    # Color must be in HEX, default is LibDoc's color
    #color: '#323b44'
    # Open Graph image file. Can be either relative URL from site root, absolute URL starting with 'http'. Default is LibDoc's splash screen
    #image: /libdoc/img/libdoc.png

# Sidebar 
sidebar:
    # Uncomment to disable search
    #disable_search: true
    # Top left branding/homepage link, specified image URL or site title if no URL is set
    logo:
        # Image URL: Can be local e.g. '/img/logo.png' or remote 'https://remotesite.com/img/logo.png'
        # url: /libdoc/img/favicon/android-chrome-512x512.png
        # Logo image max height, applies only of url is set
        max_height: 40px
        # If no logo url, font size of the site title, ignored if url is set
        #font_size: 32px
    # Display additional links anywhere into the sidebar
    additional_links:
        #-   #url: # Local or remote URL
             #title: # Link text
             #order: # Sets the rank of the page link into the sidebar, higher values give lower rank for the page link
             #category: # Add this this link into a category just like pages
        
# Badges
# Feature that allows to display badges into the footer https://shields.io image html and url
shields:
    -   image_html: <img alt="GitHub Repo stars" src="https://img.shields.io/github/stars/olivier3lanc/Scroll-Btween?logo=github&style=flat-square">
        link_url: https://github.com/olivier3lanc/Scroll-Btween

# Settings for the playground context
playground:
    metadata:
        # Sets the language of the playground, default is en
        # lang: en
        # Enable or not browser cache
        cache: false
        # Square at least 192x192 pixels icon png format
        # favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22256%22 height=%22256%22 viewBox=%220 0 100 100%22><rect width=%22100%22 height=%22100%22 rx=%2220%22 fill=%22%237d6ee7%22></rect><path fill=%22%23fff%22 d=%22M36.63 22.42L66.52 22.42Q66.78 22.87 67.06 23.63Q67.32 24.40 67.32 25.30L67.32 25.30Q67.32 26.83 66.60 27.73Q65.88 28.63 64.53 28.63L64.53 28.63L40.05 28.63L40.05 47.35L63.36 47.35Q63.63 47.80 63.91 48.56Q64.17 49.33 64.17 50.23L64.17 50.23Q64.17 51.76 63.45 52.66Q62.73 53.56 61.38 53.56L61.38 53.56L40.05 53.56L40.05 77.05Q39.60 77.23 38.66 77.41Q37.71 77.59 36.72 77.59L36.72 77.59Q32.67 77.59 32.67 74.34L32.67 74.34L32.67 26.38Q32.67 24.58 33.75 23.50Q34.84 22.42 36.63 22.42L36.63 22.42Z%22></path></svg>
        # favicon: https://olivier3lanc.github.io/folio-casa-de-papel/img/favicons/android-icon-192x192.png
        # favicon: https://preview.tabler.io/favicon.ico
        # Name of the author of the project, used into various places of the theme like footer. Default is empty
        author: Olivier Blanc
        # Theme color metadata used in some browsers like Chrome that applies this color on browser address bar.
        # Color must be in HEX, default is LibDoc's color
        color: '#206bc4'
        # Open Graph image file. Can be either relative URL from site root, absolute URL starting with 'http'. Default is LibDoc's splash screen
        #image: /img/html5_la_casa_de_papel.webp
        image: https://og-image.vercel.app/**Scroll**Btween.jpeg?theme=dark&md=1&fontSize=200px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fvercel-triangle-black.svg
    # Sets a minimum height for each playground, default is 300px
    #min_height: 600px
    # Style sheets in <head>. Can be either:
    # Relative URL from site root starting with slash /
    # Absolute URL starting with 'http'
    stylesheets: 
        #- /example-project/css/tailwind.min.css
        # - https://unpkg.com/tailwindcss@2.2.7/dist/tailwind.min.css
    # Javascript in <head>. Can be either:
    # Relative URL from site root starting with slash /
    # Absolute URL starting with 'http'
    scripts_head:
        # - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js
        # - /libdoc/js/my-toggles.js
    # Javascript at the end of <body>. Can be either:
    # Relative URL from site root starting with slash /
    # Absolute URL starting with 'http'
    scripts_body: # Javascript files near </body>. Can be either relative URL from site root, absolute URL starting with 'http'
        - /js/ola.min.js
        - /js/scroll-btween.js
        - /js/scroll-btween-debugbar.js

# Settings for the assets layout
assets:
    # The path from which files are available do download. '/' is the root
    #path_from_root: /
    # File extension to display
    extensions_enabled: 
        - pdf
        - js
        - css
        - ttf
        - woff
        - woff2
        - otf
        - zip
        - sketch
        - svg
        - jpg
        - jpeg
        - gif
        - png
        - webp
        - psd
        - ai
        - heic
        - mp4
        - webm
        - ogv
    # Array list of image extensions (without point) to display as image into asset grid
    image_extensions: 
        - svg
        - jpg
        - jpeg
        - gif
        - png
        - webp

# Settings for Prism syntax highlighter used in LibDoc
# https://prismjs.com/
prism:
    # coy, dark, funky, okaidia, twilight, solarizedlight, tomorrow, 
    theme: tomorrow
    # CSS font-size property override for <code>
    font_size: 0.9em
    # CSS line-height property override for <code>
    # line_height: 1em
    # Uncomment lines to enable language
    languages:
        - markup
        - css
        - clike
        - javascript
        #- abap
        #- abnf
        #- actionscript
        #- ada
        #- agda
        #- al
        #- antlr4
        #- apacheconf
        #- apex
        #- apl
        #- applescript
        #- aql
        #- arduino
        #- arff
        #- asciidoc
        #- aspnet
        #- asm6502
        #- autohotkey
        #- autoit
        #- bash
        #- basic
        #- batch
        #- bbcode
        #- birb
        #- bison
        #- bnf
        #- brainfuck
        #- brightscript
        #- bro
        #- bsl
        #- c
        #- csharp
        #- cpp
        #- cfscript
        #- chaiscript
        #- cil
        #- clojure
        #- cmake
        #- cobol
        #- coffeescript
        #- concurnas
        #- csp
        #- coq
        #- crystal
        #- css-extras
        #- csv
        #- cypher
        #- d
        #- dart
        #- dataweave
        #- dax
        #- dhall
        #- diff
        #- django
        #- dns-zone-file
        #- docker
        #- dot
        #- ebnf
        #- editorconfig
        #- eiffel
        #- ejs
        #- elixir
        #- elm
        #- etlua
        #- erb
        #- erlang
        #- excel-formula
        #- fsharp
        #- factor
        #- false
        #- firestore-security-rules
        #- flow
        #- fortran
        #- ftl
        #- gml
        #- gcode
        #- gdscript
        #- gedcom
        #- gherkin
        #- git
        #- glsl
        #- go
        #- graphql
        #- groovy
        #- haml
        #- handlebars
        #- haskell
        #- haxe
        #- hcl
        #- hlsl
        #- hoon
        #- http
        #- hpkp
        #- hsts
        #- ichigojam
        #- icon
        #- icu-message-format
        #- idris
        #- ignore
        #- inform7
        #- ini
        #- io
        #- j
        #- java
        #- javadoc
        #- javadoclike
        #- javastacktrace
        #- jexl
        #- jolie
        #- jq
        #- jsdoc
        #- js-extras
        #- json
        #- json5
        #- jsonp
        #- jsstacktrace
        #- js-templates
        #- julia
        #- keyman
        #- kotlin
        #- kumir
        #- latex
        #- latte
        #- less
        #- lilypond
        #- liquid
        #- lisp
        #- livescript
        #- llvm
        #- log
        #- lolcode
        #- lua
        #- makefile
        - markdown
        # - markup-templating
        #- matlab
        #- mel
        #- mizar
        #- mongodb
        #- monkey
        #- moonscript
        #- n1ql
        #- n4js
        #- nand2tetris-hdl
        #- naniscript
        #- nasm
        #- neon
        #- nevod
        #- nginx
        #- nim
        #- nix
        #- nsis
        #- objectivec
        #- ocaml
        #- opencl
        #- openqasm
        #- oz
        #- parigp
        #- parser
        #- pascal
        #- pascaligo
        #- psl
        #- pcaxis
        #- peoplecode
        #- perl
        #- php
        #- phpdoc
        #- php-extras
        #- plsql
        #- powerquery
        #- powershell
        #- processing
        #- prolog
        #- promql
        #- properties
        #- protobuf
        #- pug
        #- puppet
        #- pure
        #- purebasic
        #- purescript
        #- python
        #- qsharp
        #- q
        #- qml
        #- qore
        #- r
        #- racket
        #- jsx
        #- tsx
        #- reason
        #- regex
        #- rego
        #- renpy
        #- rest
        #- rip
        #- roboconf
        #- robotframework
        #- ruby
        #- rust
        #- sas
        #- sass
        - scss
        #- scala
        #- scheme
        #- shell-session
        #- smali
        #- smalltalk
        #- smarty
        #- sml
        #- solidity
        #- solution-file
        #- soy
        #- sparql
        #- splunk-spl
        #- sqf
        #- sql
        #- squirrel
        #- stan
        #- iecst
        #- stylus
        #- swift
        #- t4-templating
        #- t4-cs
        #- t4-vb
        #- tap
        #- tcl
        #- tt2
        #- textile
        #- toml
        #- turtle
        #- twig
        #- typescript
        #- typoscript
        #- unrealscript
        #- uri
        #- v
        #- vala
        #- vbnet
        #- velocity
        #- verilog
        #- vhdl
        #- vim
        #- visual-basic
        #- warpscript
        #- wasm
        #- wiki
        #- wolfram
        #- xeora
        # - xml-doc
        #- xojo
        #- xquery
        - yaml
        #- yang
        #- zig

# Link powered by LibDoc 
#disable_powered_by_link: true